[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "bcrypt", "@neondatabase/serverless"]

[build.environment]
  NODE_VERSION = "20"
