# Netlify Build Settings
[build]
  publish = "dist"
  command = "NODE_OPTIONS='--no-deprecation' npx convex deploy --bundle && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
